services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/academia_a1
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=academia_a1
    ports:
      - "5433:5432"
    volumes:
      # Persistencia de datos
      - db_data:/var/lib/postgresql/data
      # Script de inicialización (El usuario debe colocar su .sql en ./init-scripts/)
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
